<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1k4apYx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1k4apYx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1k4apYx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1k4apYx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1k4apYx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1k4apYx',
    'container.build_id' => '975fdea4',
    'container.build_time' => 1676030228,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1k4apYx');
